### ISSUE TITLE
🔄️[Refactor] 게시글 dto. vo (해당 기능 포함), aggregate 코드 리팩토링

### ISSUE THREAD

**Issue by jlee38266** [OmokNoonE/OnionHotSayYo-backend#44]
### 리팩토링 대상 (Refactoring Target)
'vo' 디렉토리의 파일들을 'request'와 'response'로 구분합니다. 또한 'dto' 파일들의 이름을 'vo'와의 연계성을 고려하여 적절하게 변경합니다.

### 리팩토링 이유 (Reason for Refactoring)
가변 객체와 불변 객체를 명확히 구분하여 데이터의 안정성을 보장합니다.

### 변경 내용 (Changes Made)
일부 필드값을 수정하고, 미래에 발생할 수 있는 변경에 대비하여 Lombok을 활용합니다. 해당 파일들의 목적을 클래스 윗줄에 주석으로 첨부했습니다. 'vo'와 'dto'의 수정에 따라 controller, service, serviceImpl의 코드들도 이에 맞게 수정되었습니다.
### 개선된 점 (Improvements)
Lombok을 활용하여 코드의 가독성이 향상되었고, 수정 사항이 발생했을 때 빠르게 유지보수할 수 있습니다.

### 영향 (Impact)
다른 개발자가 'dto'와 'vo'를 살펴봤을 때, 이들의 용도를 명확히 구분할 수 있습니다.

### 체크리스트 (Checklist)
- [x] 리팩토링 완료
- [x] 테스트 완료
- [x] 문서화 완료
- [x] 리뷰 요청

**Comment by orlzlL** [comment]
확인했습니다! 용도에 맞게 한 눈에 구별하기 용이할 것 같습니다.
